name: 'Pytest Coverage'
description: 'Runs pytest using uv and a specified Python version'
inputs:
  fail-under:
    description: 'Coverage fail under threshold'
    required: false
    default: '90'
  install_uv:
    description: 'Whether to install uv before running tests'
    required: false
    default: 'true'
  checkout_code:
    description: 'Whether to checkout the code before running tests'
    required: false
    default: 'true'
  install_dependencies:
    description: 'Whether to install dependencies before running tests'
    required: false
    default: 'true'
  python_version:
    description: 'Python version to use'
    required: true
    default: ''
  version-file:
    description: 'Path to the version file (e.g., pyproject.toml) to install uv from'
    required: false
    default: '.python-version'
runs:
  using: "composite"
  steps:
    - name: Checkout code
      if: ${{ inputs.checkout_code == 'true' }}
      uses: EED-Solutions/eed_gha_workflows/.github/actions/checkout_code@main
    - name: Install uv
      if: ${{ inputs.install_uv == 'true' }}
      uses: EED-Solutions/eed_gha_workflows/.github/actions/install_uv@main
      with:
        enable-cache: true
        python-version: ${{ inputs.python_version }}
        version-file: ${{ inputs.version-file }}
    - name: Install dependencies
      if: ${{ inputs.install_dependencies == 'true' }}
      uses: EED-Solutions/eed_gha_workflows/.github/actions/set_up_py_env@main
    - name: Run pytests
      shell: bash
      run: |
        uv run --frozen pytest --cov=src --cov-fail-under=${{inputs.fail-under}} --cov-report=term-missing  tests
