name: 'Callable Ruff'
description: 'Runs Ruff linter with uv setup'
inputs:
  branch_name:
    description: 'Branch name to check if it is main'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Echo environment
      shell: bash
      run: |
        echo "GITHUB_REF=${GITHUB_REF}"
        echo "BRANCH_NAME=${{ inputs.branch_name }}"
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Ruff
      uses: astral-sh/ruff-action@v3
    - name: Run Ruff
      shell: bash
      run: uv run ruff check --output-format=github
