name: 'Callable Pytests'
description: 'Runs pytest using uv and a specified Python version'
inputs:
  python_version:
    description: 'Python version to use'
    required: true
    default: '3.12'
  checkout_code:
    description: 'Whether to checkout the code before running tests'
    required: false
    default: 'true'
  install_uv:
    description: 'Whether to install uv before running tests'
    required: false
    default: 'true'
  install_dependencies:
    description: 'Whether to install dependencies before running tests'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Checkout code
      if: ${{ inputs.checkout_code == 'true' }}
      uses: actions/checkout@v4
    - name: Install uv
      if: ${{ inputs.install_uv == 'true' }}
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: ${{ inputs.python_version }}
    - name: Install dependencies
      if: ${{ inputs.install_dependencies == 'true' }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        uv sync
    - name: Run pytests
      shell: bash
      run: |
        uv run --frozen pytest tests
