name: 'Callable Pytests'
description: 'Runs pytest using uv and a specified Python version'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.12'
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        uv sync

    - name: Run pytests
      shell: bash
      run: |
        uv run pytest tests
