name: callable_pytests_cov

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string

jobs:
  callable_pytests_cov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv # https://eed-solutions.atlassian.net/wiki/spaces/ES/pages/782434388/Best+Practice+uv+package+management#Github-Actions
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          uv sync
      - name: Run pytests
        run: |
          uv run pytest --cov=${{ inputs.package_name }} tests/
